parameters:
    liuggio_stats_d_client.event_listener.class: Liuggio\StatsDClientBundle\EventListener\StatsdListener

services:
    liuggio_stats_d_client.event_listener:
        class: %liuggio_stats_d_client.event_listener.class%
        arguments:
            - @liuggio_stats_d_client.data_collector
            - @liuggio_stats_d_client.client
        tags:
            - { name: kernel.event_subscriber }
